### ISSUE TITLE
overlapping config in epmg-energy-scenarios and the individual scenario

### ISSUE THREAD

**Issue by energynumbers** [MaREI-EPMG/epmg-energy-scenarios#3]
I notice that `epmpg-website/src/specs/scenarios.js` seems to contain overlapping information with `tim-carbon-budgets-2022/specs/scenarios.json`.

Is `scenarios.js` auto-generated? Does it draw from `scenarios.json`?

**Comment by olejandro** [comment]
No, ``scenaios.js`` is just a temporary measure to make sure all the scenarios are loaded. It will be depreceated once all the studies currently displayed get their own ``scenarios.json`` :-)

**Comment by energynumbers** [comment]
Ah, ok, good to know.

**Comment by olejandro** [comment]
Let's keep this open for now...

**Comment by energynumbers** [comment]
I think this is pretty much dealt with now.
