### ISSUE TITLE
would it be possible to embed scenario name in URL for direct linking into scenario charts?

### ISSUE THREAD

**Issue by energynumbers** [MaREI-EPMG/epmg-energy-scenarios#4]
e.g. - current URL structure is `https://epmg.netlify.app/tim-carbon-budgets-2022/results/overview/other`

Would it be possible to have something like:

`https://epmg.netlify.app/tim-carbon-budgets-2022/results/overview/other#Mitigation_CarbonBudget-TechOptimism/Mitigation_SectoralCBs-LED_Halfway`

Which would then show those charts, comparing those two specific scenarios?

**Comment by olejandro** [comment]
Yes, the plan is introduce query strings, so that one can share individual charts or tabs with preselected scenario(s). Would it be good to prioritise it?

**Comment by energynumbers** [comment]
No, definitely no need to prioritise it. If you can point me at the right place to start looking, I might attempt it myself.

**Comment by energynumbers** [comment]
I've now submitted a patch to do this: facilitate-energy/energy-charts#29

**Comment by olejandro** [comment]
The following works: https://epmg.netlify.app/tim-carbon-budgets-2022/results/overview/other?scen1=Mitigation_CarbonBudget-TechOptimism&scen2=Mitigation_SectoralCBs-LED_Halfway&diff=true
In case some of the search parameters are not valid:
- scen1: the top most scenario will be selected
- scen2: no scenario for comparison will be selected and diff will be set to false
- diff: will be set to false

**Comment by energynumbers** [comment]
Hi @olejandro , this doesn't seem to change the URL when scenarios are selected, or the show-difference button is toggled.

That is, it only does half the job. It reads URL parameters, but doesn't set them.

**Comment by olejandro** [comment]
Hi @energynumbers, why should it change the URL when scenarios are selected? I.e. this let's you share a page with specific scenarios selected. Is this not what was desired?

**Comment by energynumbers** [comment]
@olejandro It's only half of what's desired.

As per my patch at facilitate-energy#29 it should change the URL when scenarios are selected and when the show-difference button is toggled: this creates the URL which can then be shared.

**Comment by olejandro** [comment]
@energynumbers, I see. 🤷‍♂️
